workflows:
  ios-workflow:
    name: Build Call Tracker+ App
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        APP_ID: "com.dynastybuildersacademy.calltrackerplus"
        BUNDLE_ID: "com.dynastybuildersacademy.calltrackerplus"
      groups:
        - app_store_credentials
        - google_credentials
      ios_signing:
        distribution_type: app_store
        bundle_identifier: "com.dynastybuildersacademy.calltrackerplus"
    scripts:
      - name: Install Dependencies
        script: flutter pub get
      - name: Run Tests
        script: flutter test
      - name: Build iOS (.ipa)
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
