
workflows:
  ios-signing-automated:
    name: iOS Auto Signing
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: "com.dynastybuildersacademy.calltrackerplus"
    integrations:
      app_store_connect: app_store_credentials
    ios_signing:
      distribution_type: app_store
      bundle_identifier: $BUNDLE_ID
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build IPA
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
