workflows:
  ios-workflow:
    name: Build Call Tracker+ App
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      vars:
        APP_ID: "com.dynastybuildersacademy.calltrackerplus"
        BUNDLE_ID: "com.dynastybuildersacademy.calltrackerplus"
      groups:
        - app_store_credentials
      ios_signing:
        distribution_type: app_store
        bundle_identifier: "com.dynastybuildersacademy.calltrackerplus"
    integrations:
      app_store_connect: app_store_credentials

    scripts:
      - name: Print API Key Env Vars (Test Only)
        script: |
          echo "Key ID: $APP_STORE_CONNECT_KEY_ID"
          echo "Issuer ID: $APP_STORE_CONNECT_ISSUER_ID"
          echo "Private Key (start):"
          echo "$APP_STORE_CONNECT_PRIVATE_KEY" | cut -c -40

      - name: Install Dependencies
        script: flutter pub get

      - name: Run Tests
        script: flutter test

      - name: Build Android (.aab)
        script: flutter build appbundle --release --build-name=1.0.0 --build-number=1

      - name: Build iOS (.ipa)
        script: flutter build ipa --release

    artifacts:
      - build/**/outputs/**/*.aab
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
