
name: call_tracker_plus
description: A personal assistant app for insurance agents.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^15.1.1
  google_sign_in: ^6.1.5
  table_calendar: ^3.1.0
  http: ^0.13.6
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
