
name: call_tracker_plus
description: Call Tracker+ full logic with GitHub-ready setup.
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^12.0.0
  google_sign_in: ^6.1.4
  http: ^0.13.6
  intl: ^0.18.1
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
